# Generated by Django 5.0.6 on 2026-08-08 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('practice', 'Practice'), ('mock_exam', 'Mock Exam'), ('flashcard', 'Flashcard')], db_index=True, max_length=12)),
                ('subject_name', models.CharField(max_length=120)),
                ('topic_label', models.CharField(blank=True, default='', max_length=200)),
                ('question_type', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('render_data', models.JSONField(blank=True, default=dict)),
                ('your_answer_text', models.TextField()),
                ('correct_answer_text', models.TextField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('hint', models.TextField(blank=True, default='')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_retried_at', models.DateTimeField(blank=True, null=True)),
                ('last_retry_correct', models.BooleanField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='mistakes_mi_user_id_d931cf_idx'), models.Index(fields=['user', 'source'], name='mistakes_mi_user_id_3c2341_idx')],
            },
        ),
    ]
