# Generated by Django 5.0.6 on 2026-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakeentry',
            name='mistake_type',
            field=models.CharField(choices=[('not_attempted', 'Not Attempted'), ('incorrect', 'Incorrect')], db_index=True, default='incorrect', max_length=20),
        ),
    ]
