# Generated by Django 5.0.6 on 2026-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0002_mistakeentry_mistake_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakeentry',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mistakeentry',
            name='error_category',
            field=models.CharField(choices=[('unclassified', 'Not yet classified'), ('careless_slip', 'Careless slip'), ('conceptual_gap', 'Conceptual gap'), ('process_error', 'Process error'), ('misread_question', 'Misread question')], db_index=True, default='unclassified', max_length=20),
        ),
        migrations.AddField(
            model_name='mistakeentry',
            name='error_explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
