# Generated by Django 5.0.6 on 2026-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='Null = due now (never reviewed).', null=True),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
