# Generated by Django 5.0.6 on 2026-08-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_audio_flashcard_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English')], db_index=True, default='math', max_length=20),
        ),
    ]
