# Generated by Django 5.0.6 on 2026-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_flashcarddeck_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='translation',
            field=models.TextField(blank=True, default='', help_text='Armenian translation of front_text, shown alongside it.'),
        ),
    ]
