# Generated by Django 5.0.6 on 2026-08-18 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('games', '0013_merge_20260815_2044'),
        ('practice', '0005_merge_0003_question_passage_0004_topicmistake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challengeinvite',
            index=models.Index(fields=['receiver', 'status'], name='challenges__receive_2fa5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinvite',
            index=models.Index(fields=['sender', 'status'], name='challenges__sender__e0c1f0_idx'),
        ),
    ]
