# Generated by Django 5.0.6 on 2026-08-18 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengeinvite_challenges__receive_2fa5e6_idx_and_more'),
        ('games', '0014_gameroom_games_gamer_type_088a55_idx'),
        ('practice', '0005_merge_0003_question_passage_0004_topicmistake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challengeinvite',
            index=models.Index(fields=['status', 'expires_at'], name='challenges__status_a56f5b_idx'),
        ),
    ]
