# Generated by Django 5.0.6 on 2026-08-04 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_marz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('school', 'School')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('xp', models.PositiveIntegerField(help_text='XP the user had for that month when the award was granted.')),
                ('title', models.CharField(max_length=150)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, help_text='Null for global-scope awards.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_awards', to='users.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month', '-xp'], name='rankings_monthlyxp_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyxp',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_monthly_xp_per_user'),
        ),
        migrations.AddConstraint(
            model_name='rankingaward',
            constraint=models.UniqueConstraint(fields=('scope', 'school', 'year', 'month', 'rank'), name='unique_ranking_award_slot'),
        ),
    ]
