# Generated by Django 5.0.6 on 2026-08-06 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
        ('users', '0004_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rankingaward',
            name='unique_ranking_award_slot',
        ),
        migrations.AddField(
            model_name='rankingaward',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set only for class-scope awards.', null=True),
        ),
        migrations.AlterField(
            model_name='rankingaward',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('school', 'School'), ('class', 'Class')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='rankingaward',
            constraint=models.UniqueConstraint(fields=('scope', 'school', 'grade', 'year', 'month', 'rank'), name='unique_ranking_award_slot'),
        ),
    ]
