# Generated by Django 5.0.6 on 2026-08-08 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_remove_rankingaward_unique_ranking_award_slot_and_more'),
        ('users', '0005_user_username_changed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('school', 'School'), ('class', 'Class')], max_length=10)),
                ('scope_key', models.CharField(help_text='Disambiguates GLOBAL / SCHOOL:<id> / CLASS:<school_id>:<grade> for uniqueness without relying on nullable FK combinations.', max_length=64)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('xp', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['user', 'scope_key', '-date'], name='rankings_rankhistory_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rankhistory',
            constraint=models.UniqueConstraint(fields=('user', 'scope_key', 'date'), name='unique_rank_history_per_day'),
        ),
    ]
