# Generated by Django 5.0.6 on 2026-08-08 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_rankhistory_rankhistory_unique_rank_history_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subject XP',
                'indexes': [models.Index(fields=['subject_key', 'year', 'month', '-xp'], name='rankings_subjectxp_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectxp',
            constraint=models.UniqueConstraint(fields=('user', 'subject_key', 'year', 'month'), name='unique_subject_xp_per_user_month'),
        ),
    ]
