# Generated by Django 5.0.6 on 2026-08-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotification',
            name='notification_type',
            field=models.CharField(choices=[('rank_up', 'Rank improved'), ('overtaken', 'Overtaken in ranking'), ('season_ending', 'Season ending soon'), ('season_result', 'Season result'), ('challenge_received', 'Challenge received'), ('challenge_result', 'Challenge result'), ('friend_added', 'New friend'), ('parent_link_accepted', 'Child accepted parent link request')], max_length=30),
        ),
    ]
