# Generated by Django 5.0.6 on 2026-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_studentnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotification',
            name='notification_type',
            field=models.CharField(choices=[('rank_up', 'Rank improved'), ('overtaken', 'Overtaken in ranking'), ('season_ending', 'Season ending soon'), ('season_result', 'Season result'), ('challenge_received', 'Challenge received'), ('challenge_result', 'Challenge result'), ('friend_added', 'New friend'), ('parent_link_accepted', 'Child accepted parent link request'), ('message_request', 'New message request'), ('mention', 'Mentioned in chat'), ('group_invite', 'Added to a group'), ('todo_reminder', 'To-do reminder')], max_length=30),
        ),
    ]
