# Generated by Django 5.0.6 on 2026-08-18 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_studentnotification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentnotification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_dc1df3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnotification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_2626a9_idx'),
        ),
    ]
