# Generated by Django 5.0.6 on 2026-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='sent', max_length=10),
        ),
    ]
