# Generated by Django 5.0.6 on 2026-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text="Student's write-up of what they learned, sent with submission."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_feedback',
            field=models.TextField(blank=True, default='', help_text='Optional note from the teacher when rejecting a submission.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='assigned', max_length=15),
        ),
    ]
