# Generated by Django 5.0.6 on 2026-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_assignment_explanation_assignment_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='learning_progress',
            field=models.FloatField(default=0.0, help_text="Fraction (0-1) of the subtopic's learning material the student has scrolled through. Only meaningful for assignment_type=subtopic."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='seen_by_student',
            field=models.BooleanField(default=False, help_text="False right after creation or after a teacher review — drives the student's notification bell."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='seen_by_teacher',
            field=models.BooleanField(default=True, help_text="False right after a student submission — drives the teacher's notification bell."),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
