# Generated by Django 5.0.6 on 2026-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_assignment_learning_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='progress_reset_at',
            field=models.DateTimeField(blank=True, help_text='Progress/completion only counts practice attempts made after this (falls back to created_at). Bumped to now() when the student redoes a rejected assignment, so old completions from before the redo stop counting without touching the underlying practice data.', null=True),
        ),
    ]
