# Generated by Django 5.0.6 on 2026-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('questions_solved', 'Questions solved (lifetime correct answers)'), ('perfect_score', 'Best practice-tier score reached (0-100)'), ('streak_days', 'Longest learning streak (days)')], default='questions_solved', max_length=40),
        ),
        migrations.AddField(
            model_name='achievement',
            name='requirement_value',
            field=models.PositiveIntegerField(default=0, help_text="Threshold the requirement_type's metric must reach/exceed."),
        ),
    ]
