# Generated by Django 5.0.6 on 2026-07-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_seed_game_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('questions_solved', 'Questions solved (lifetime correct answers)'), ('perfect_score', 'Best practice-tier score reached (0-100)'), ('streak_days', 'Longest learning streak (days)'), ('games_played', 'Multiplayer games played (lifetime)'), ('games_won', 'Multiplayer games won (lifetime)')], default='questions_solved', max_length=40),
        ),
    ]
