# Generated by Django 5.0.6 on 2026-08-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_achievement_requirement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_exam_date',
            field=models.DateField(blank=True, help_text='User-set date of their entrance exam, for the countdown.', null=True),
        ),
    ]
