# Generated by Django 5.0.6 on 2026-08-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_target_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_code',
            field=models.CharField(blank=True, help_text='Shareable code a parent enters to link this account. Generated lazily on first request.', max_length=8, null=True, unique=True),
        ),
    ]
