# Generated by Django 5.0.6 on 2026-08-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_family_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='family_code',
        ),
    ]
