# Generated by Django 5.0.6 on 2026-08-08 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_merge_0003_question_passage_0004_topicmistake'),
        ('profiles', '0009_remove_profile_family_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_major',
            field=models.CharField(blank=True, default='', help_text="Free-text target major/program, e.g. 'Computer Science'.", max_length=200),
        ),
        migrations.CreateModel(
            name='PersonalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('subject_accuracy', 'Accuracy in a subject (%)'), ('tests_this_week', 'Mock exams completed this week'), ('streak_days', 'Learning streak (days)'), ('study_hours_month', 'Study hours this month'), ('xp_this_month', 'XP earned this month'), ('custom', 'Custom (self-reported)')], max_length=20)),
                ('target_value', models.PositiveIntegerField(default=0, help_text='Tests, streak days, study hours, XP, or accuracy % depending on goal_type. Unused for custom goals.')),
                ('custom_title', models.CharField(blank=True, default='', help_text='Required for custom goals; ignored otherwise.', max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Required for subject_accuracy goals; ignored otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_school', models.BooleanField(default=True)),
                ('show_age', models.BooleanField(default=False)),
                ('show_university', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_ranking', models.BooleanField(default=True)),
                ('show_achievements', models.BooleanField(default=True)),
                ('show_friends', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowcaseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='0, 1, or 2 — display order.')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcased_in', to='profiles.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'achievement'), ('user', 'position')},
            },
        ),
    ]
