# Generated by Django 5.0.6 on 2026-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_target_major_personalgoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprivacysettings',
            name='show_on_leaderboard',
            field=models.BooleanField(default=True, help_text="Whether this user appears in other users' global/school/class/friends leaderboards at all. Distinct from show_ranking, which only gates the medals/trophy case shown on their own profile — this one opts them out of the leaderboard lists themselves. They can always still see their own position privately even when this is off."),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='show_ranking',
            field=models.BooleanField(default=True, help_text="Show this user's ranking medals/trophy case on their profile."),
        ),
    ]
