# Generated by Django 5.0.6 on 2026-08-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profileprivacysettings_show_on_leaderboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalgoal',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form structured extras for consuming systems (e.g. future AI context/study-planner). Not read or interpreted here.'),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
