# Generated by Django 5.0.6 on 2026-08-11 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_personalgoal_metadata_personalgoal_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Bakalavriat mathematics', 'SAT'.", max_length=200)),
                ('subject_key', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English')], default='', help_text='Canonical subject key (see apps.profiles.subjects.SUBJECT_LABELS). Blank for multi-subject exams.', max_length=20)),
                ('exam_date', models.DateField()),
                ('target_score', models.PositiveIntegerField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('topics_note', models.TextField(blank=True, default='', help_text='Freeform note on which topics this exam covers.')),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('target_note', models.CharField(blank=True, default='', help_text="Freeform target, e.g. 'score 90+ on entrance exam'.", max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, help_text='The upcoming exam this subject is being studied for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_subjects', to='profiles.studentexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text='List of ISO weekday ints the student prefers to study, 0=Monday..6=Sunday.')),
                ('preferred_start_time', models.TimeField(blank=True, help_text='Student-declared preferred time of day to start studying.', null=True)),
                ('typical_session_minutes', models.PositiveIntegerField(blank=True, help_text='Student-declared typical/preferred single-session length.', null=True)),
                ('min_daily_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_daily_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(fields=('user', 'subject_key'), name='unique_student_subject_per_user'),
        ),
    ]
