# Generated by Django 5.0.6 on 2026-08-11 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('profiles', '0013_studentexam_studentsubject_studyavailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('topic_studied', 'Topic studied'), ('lesson_started', 'Lesson started'), ('lesson_completed', 'Lesson completed'), ('question_attempted', 'Question attempted'), ('question_answered', 'Question answered'), ('test_completed', 'Test completed'), ('study_session_started', 'Study session started'), ('study_session_completed', 'Study session completed'), ('explanation_requested', 'Explanation requested'), ('hint_requested', 'Hint requested'), ('concept_reviewed', 'Concept reviewed'), ('exam_completed', 'Exam completed')], max_length=30)),
                ('subject_key', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English')], default='', max_length=20)),
                ('topic_label', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', help_text="Which app/system recorded this, e.g. 'practice', 'ai_assistant', 'mock_exams'.", max_length=30)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text="Id of the referenced row in its own app's table (e.g. a PracticeAttempt id), if any.", null=True)),
                ('result', models.CharField(blank=True, default='', help_text="Short outcome label, e.g. 'correct', 'incorrect', 'completed'.", max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='activity.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='profiles_le_user_id_738bc5_idx'), models.Index(fields=['user', 'event_type', '-occurred_at'], name='profiles_le_user_id_760888_idx'), models.Index(fields=['user', 'subject_key'], name='profiles_le_user_id_b06f53_idx')],
            },
        ),
    ]
