# Generated by Django 5.0.6 on 2026-08-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_learningevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_style', models.CharField(choices=[('direct', 'Direct — explain fully, no back-and-forth'), ('socratic', 'Socratic — guided questions before the answer'), ('mixed', 'Mixed — let the AI Tutor choose per situation')], default='mixed', max_length=20)),
                ('hints_before_answers', models.BooleanField(default=True, help_text='Whether the AI Tutor should nudge with hints before revealing full solutions.')),
                ('preferred_language', models.CharField(blank=True, default='', help_text="ISO language code the student wants the AI Tutor to respond in, e.g. 'hy', 'en'. Blank = no preference.", max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
