# Generated by Django 5.0.6 on 2026-08-17 20:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_learningpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_exams_per_week', models.PositiveSmallIntegerField(default=1, help_text='How many full mock exams the coach may propose in a week. 0 disables them entirely.', validators=[django.core.validators.MaxValueValidator(7)])),
                ('preferred_test_days', models.JSONField(blank=True, default=list, help_text='ISO weekday ints a full exam is welcome on, 0=Monday..6=Sunday. Empty = any day.')),
                ('preferred_test_time', models.TimeField(blank=True, help_text='Time of day the student prefers to sit a full exam.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
