# Generated by Django 5.0.6 on 2026-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_coachpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachpreferences',
            name='configured_at',
            field=models.DateTimeField(blank=True, help_text='When the student first saved this deliberately. The row itself is created on read with working defaults, so its existence proves nothing; without this, a student who genuinely wants the default cadence can never satisfy the profile-completeness prompt asking them to choose one.', null=True),
        ),
    ]
