# Generated by Django 5.0.6 on 2026-08-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('question_count', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'exam_id'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='None = untimed.', null=True)),
                ('hints_enabled', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('time_remaining_seconds', models.IntegerField(blank=True, help_text='Snapshot of remaining time as of the last draft save.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.PositiveIntegerField(blank=True, null=True)),
                ('scaled_score', models.FloatField(blank=True, null=True)),
                ('percent_answered', models.FloatField(blank=True, null=True)),
                ('easy_correct', models.PositiveIntegerField(default=0)),
                ('easy_total', models.PositiveIntegerField(default=0)),
                ('medium_correct', models.PositiveIntegerField(default=0)),
                ('medium_total', models.PositiveIntegerField(default=0)),
                ('hard_correct', models.PositiveIntegerField(default=0)),
                ('hard_total', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mock_exams.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Display order within the exam (1-65).')),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('group', models.CharField(blank=True, default='', help_text='Informational clustering key from the source JSON; not rendered specially.', max_length=100)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('free_response', 'Free Response'), ('multi_statement', 'Multi Statement')], max_length=20)),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('hint', models.TextField(blank=True, default='')),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('correct_answer_text', models.TextField(blank=True, default='')),
                ('dataset_id', models.CharField(max_length=100, unique=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock_exams.mockexam')),
            ],
            options={
                'ordering': ['exam', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MockExamChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mock_exams.mockexamquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockExamStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Armenian letter, e.g. 'Ա', 'Բ', ...", max_length=10)),
                ('text', models.TextField()),
                ('is_true', models.BooleanField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='mock_exams.mockexamquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, help_text='Null until the attempt is finished.', null=True)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('selected_statement_ids', models.JSONField(blank=True, default=list)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mock_exams.mockexamattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mock_exams.mockexamchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_exams.mockexamquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
