# Generated by Django 5.0.6 on 2026-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockexam',
            options={'ordering': ['subject', 'order', 'exam_id']},
        ),
        migrations.AddField(
            model_name='mockexam',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics')], db_index=True, default='math', max_length=20),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='figure_svg',
            field=models.TextField(blank=True, default=''),
        ),
    ]
