# Generated by Django 5.0.6 on 2026-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0002_alter_mockexam_options_mockexam_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexam',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology')], db_index=True, default='math', max_length=20),
        ),
    ]
