# Generated by Django 5.0.6 on 2026-08-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0003_alter_mockexam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexamanswer',
            name='match_pairs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mockexamstatement',
            name='match_target',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('free_response', 'Free Response'), ('multi_statement', 'Multi Statement'), ('matching', 'Matching')], max_length=20),
        ),
    ]
