# Generated by Django 5.0.6 on 2026-08-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0004_mockexamanswer_match_pairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexam',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry')], db_index=True, default='math', max_length=20),
        ),
    ]
