# Generated by Django 5.0.6 on 2026-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0005_alter_mockexam_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexam',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English')], db_index=True, default='math', max_length=20),
        ),
    ]
