# Generated by Django 5.0.6 on 2026-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_school_university_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
