# Generated by Django 5.0.6 on 2026-08-03 19:55
# Merged: combines the "student/teacher" and "student/parent" role additions
# from two branches into a single student/teacher/parent field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_marz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('student', 'Աշակերտ'), ('teacher', 'Ուսուցիչ'), ('parent', 'Ծնող')],
                default='student',
                max_length=10,
            ),
        ),
    ]
