# Generated by Django 5.0.6 on 2026-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_marz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Աշակերտ'), ('parent', 'Ծնող')], default='student', max_length=10),
        ),
    ]
