# Generated by Django 5.0.6 on 2026-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
