# Generated by Django 5.0.6 on 2026-08-11 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0005_merge_0003_question_passage_0004_topicmistake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(blank=True, help_text='0-100, recency-weighted accuracy.', null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('data_sufficiency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_scores', to='practice.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mastery_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('english', 'English')], max_length=20)),
                ('mastery_score', models.FloatField(blank=True, help_text='0-100, recency-weighted accuracy. Null = no data yet.', null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('data_sufficiency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mastery_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_key'], name='knowledge_s_user_id_8ba3b0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectmastery',
            constraint=models.UniqueConstraint(fields=('user', 'subject_key'), name='unique_subject_mastery_per_user'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['user', 'subtopic'], name='knowledge_t_user_id_067adc_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.UniqueConstraint(fields=('user', 'subtopic'), name='unique_topic_mastery_per_user'),
        ),
    ]
