# Generated by Django 5.0.6 on 2026-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmastery',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='next_review_at',
            field=models.DateTimeField(blank=True, help_text='Null = due now (never scheduled, or interval reset to 0).', null=True),
        ),
    ]
