# Generated by Django 5.0.6 on 2026-08-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('task_type', models.CharField(choices=[('flashcard_review', 'Flashcard Review'), ('practice_weak_topic', 'Practice Weak Topic'), ('mistake_retry', 'Mistake Retry'), ('mock_exam_retake', 'Mock Exam Retake')], max_length=25)),
                ('subject_name', models.CharField(max_length=120)),
                ('topic_label', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('blurb', models.TextField(blank=True, default='')),
                ('link_path', models.CharField(max_length=200)),
                ('target_id', models.PositiveIntegerField()),
                ('params', models.JSONField(blank=True, default=dict)),
                ('target_count', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_plan.dailystudyplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
