# Generated by Django 5.0.6 on 2026-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudyplan',
            name='coach_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
