# Generated by Django 5.0.6 on 2026-08-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_dailystudyplan_coach_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('great', 'Great'), ('ok', 'OK'), ('struggled', 'Struggled')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='study_plan.studytask')),
            ],
        ),
    ]
