# Generated by Django 5.0.6 on 2026-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0004_weeklycoachreportdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytask',
            name='link_path',
            field=models.TextField(),
        ),
    ]
