# Generated by Django 5.0.6 on 2026-08-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('canvas', 'Canvas')], default='rich_text', max_length=20),
        ),
    ]
