# Generated by Django 5.0.6 on 2026-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='min_players_to_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='start_condition',
            field=models.CharField(choices=[('manual', 'Manual'), ('timer', 'Timer'), ('player_count', 'When enough players join')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='timer_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
