# Generated by Django 5.0.6 on 2026-07-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameroom_min_players_to_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_mode', models.CharField(choices=[('player_count', 'Start after X players join'), ('timer', 'Start after a timer')], max_length=20)),
                ('min_players', models.PositiveSmallIntegerField(default=10)),
                ('max_players', models.PositiveSmallIntegerField(default=50)),
                ('timer_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='matchmaking_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='games.matchmakingqueue'),
        ),
        migrations.CreateModel(
            name='MatchmakingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('cancelled', 'Cancelled')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='games.matchmakingqueue')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchmaking_tickets', to='games.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchmakingticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('user', 'queue'), name='unique_waiting_ticket_per_user_queue'),
        ),
    ]
