# Generated by Django 5.0.6 on 2026-07-27 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_seed_matchmaking_queues'),
        ('practice', '0002_statement_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveSmallIntegerField()),
                ('easy_count', models.PositiveSmallIntegerField(default=0)),
                ('medium_count', models.PositiveSmallIntegerField(default=0)),
                ('hard_count', models.PositiveSmallIntegerField(default=0)),
                ('time_limit_per_question', models.PositiveIntegerField(help_text='Seconds')),
                ('total_game_time', models.PositiveIntegerField(blank=True, help_text='Seconds; optional overall cap', null=True)),
                ('allow_mixed_question_types', models.BooleanField(default=True)),
                ('question_types', models.JSONField(blank=True, default=list, help_text='Subset of practice.QuestionType values allowed in this game.')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='games.gameroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='practice.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='practice.topic')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='practice.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='games.gameroom')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('room', 'order'), ('room', 'question')},
            },
        ),
    ]
