# Generated by Django 5.0.6 on 2026-07-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamesettings_gamequestion'),
        ('practice', '0002_statement_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipant',
            name='current_question_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('selected_statement_ids', models.JSONField(blank=True, default=list)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('game_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.gamequestion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.gameparticipant')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.choice')),
            ],
            options={
                'unique_together': {('participant', 'game_question')},
            },
        ),
    ]
