# Generated by Django 5.0.6 on 2026-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gameparticipant_current_question_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameparticipant',
            name='current_question_index',
        ),
        migrations.RemoveField(
            model_name='gameparticipant',
            name='current_question_started_at',
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='current_question_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
