# Generated by Django 5.0.6 on 2026-07-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_gameparticipant_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanswer',
            name='time_taken_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='newly_unlocked_achievement_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
