# Generated by Django 5.0.6 on 2026-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gameanswer_time_taken_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipant',
            name='average_response_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='unanswered_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='correctness_weight',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='speed_weight',
            field=models.FloatField(default=0.2),
        ),
    ]
