# Generated by Django 5.0.6 on 2026-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_gameparticipant_average_response_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipant',
            name='trophies_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='participant_count_at_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='trophies_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='trophies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
