# Generated by Django 5.0.6 on 2026-08-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gameparticipant_trophies_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='current_question_index',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='current_question_started_at',
        ),
        migrations.RemoveField(
            model_name='gamesettings',
            name='time_limit_per_question',
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='current_question_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='speed_bonus_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='time_taken_to_finish_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='easy_time_limit',
            field=models.PositiveIntegerField(default=15, help_text='Seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='medium_time_limit',
            field=models.PositiveIntegerField(default=20, help_text='Seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='hard_time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Seconds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='total_game_time',
            field=models.PositiveIntegerField(blank=True, help_text="Seconds; optional overall cap from room start after which any still-in-progress participant is force-finished. If unset, an implicit cap (sum of every question's own tier time limit) is used instead — see services.effective_total_game_time — so a vanished/AFK participant can never block the room from ever settling for everyone else.", null=True),
        ),
    ]
