# Generated by Django 5.0.6 on 2026-08-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_gameroom_current_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
