# Generated by Django 5.0.6 on 2026-08-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gameroom_finished_at_suspiciousactivitylog'),
        ('games', '0012_alter_gameroom_status'),
    ]

    operations = [
    ]
