# Generated by Django 5.0.6 on 2026-08-18 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_merge_20260815_2044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['type', 'status'], name='games_gamer_type_088a55_idx'),
        ),
    ]
