# Generated by Django 5.0.6 on 2026-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagereaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='context_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='context_type',
            field=models.CharField(blank=True, choices=[('mock_exam_result', 'Mock exam result'), ('achievement', 'Achievement'), ('profile', 'Profile')], max_length=20, null=True),
        ),
    ]
