# Generated by Django 5.0.6 on 2026-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_context_data_message_context_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
