# Generated by Django 5.0.6 on 2026-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_description_conversation_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('text', 'Text'), ('audio', 'Audio'), ('other', 'Other')], max_length=10),
        ),
    ]
