# Generated by Django 5.0.6 on 2026-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_attachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='context_type',
            field=models.CharField(blank=True, choices=[('mock_exam_result', 'Mock exam result'), ('achievement', 'Achievement'), ('profile', 'Profile'), ('challenge', 'Challenge')], max_length=20, null=True),
        ),
    ]
