# Generated by Django 5.0.6 on 2026-08-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_attachment_file_type_and_more'),
        ('chat', '0010_alter_message_context_type'),
    ]

    operations = [
    ]
