# Generated by Django 5.0.6 on 2026-08-07 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_dailyproblemattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('practice', 'Practice'), ('mock_exam', 'Mock Exam')], max_length=10)),
                ('subject_name', models.CharField(max_length=120)),
                ('topic_label', models.CharField(max_length=200)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('last_incorrect_at', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mistakes', to=settings.AUTH_USER_MODEL)),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='practice.subtopic')),
            ],
            options={
                'ordering': ['-incorrect_count', '-last_incorrect_at'],
                'unique_together': {('student', 'source', 'subject_name', 'topic_label')},
            },
        ),
    ]
