# Generated by Django 5.0.6 on 2026-08-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_question_passage'),
        ('practice', '0004_topicmistake'),
    ]

    operations = [
    ]
