# Generated by Django 5.0.6 on 2026-08-18 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['subject', 'type'], name='study_group_subject_a64922_idx'),
        ),
    ]
